package org.clevercastle.saas.core.internal.exception

class NotFoundException(message: String) : RuntimeException(message)